version: '3.3'

services:
  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"

  mini-blog:
    build: ./
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      DB_URL: mongodb://mongodb/miniBlog
      SECRET: xxxx
